const GAME_PICK = "GAME_PICK"
const GAME_START = "GAME_START"
const GAME_RESTART = "GAME_RESTART"
const GAME_SET_NICK_NAME = "GAME_SET_NICK_NAME"
const GAME_SET_STATE = "GAME_SET_STATE"

export default {
  GAME_PICK,
  GAME_START,
  GAME_RESTART,
  GAME_SET_NICK_NAME,
  GAME_SET_STATE
}