const GAME_PICK = "GAME_PICK"
const GAME_SET_NICK_NAME = "GAME_SET_NICK_NAME"
const GAME_SET_STATE = "GAME_SET_STATE"
const GAME_GENERATE_CHUNKS = "GAME_GENERATE_CHUNKS"
const GAME_GENERATE_CLASSES = "GAME_GENERATE_CLASSES"
const GAME_SET_POINT = "GAME_SET_POINT"

export default {
  GAME_PICK,
  GAME_SET_NICK_NAME,
  GAME_SET_STATE,
  GAME_GENERATE_CHUNKS,
  GAME_GENERATE_CLASSES,
  GAME_SET_POINT
}